code --install-extension ms-python.python 
code --install-extension ms-python.black-formatter 
code --install-extension ms-vscode.cpptools 
code --install-extension ms-iot.vscode-ros 
code --install-extension ms-vscode.cmake-tools 
code --install-extension twxs.cmake 
code --install-extension ms-azuretools.vscode-docker 
code --install-extension ms-vscode.remote-containers 
code --install-extension ms-vscode.remote-ssh 
code --install-extension ms-vscode.remote-explorer 
code --install-extension ms-vscode.github 
code --install-extension eamodio.gitlens 
code --install-extension github.vscode-github-actions 
code --install-extension github.copilot 
code --install-extension github.copilot-chat 
code --install-extension github.vscode-pull-request-github 
code --install-extension redhat.vscode-yaml 
code --install-extension davidanson.vscode-markdownlint 
code --install-extension streetsidesoftware.code-spell-checker 
code --install-extension foxundermoon.shell-format 
code --install-extension timonwong.shellcheck 
code --install-extension ms-vscode.vscode-typescript-tslint-plugin 
code --install-extension ms-vscode.makefile-tools 
code --install-extension ms-vscode.cpptools-extension-pack 
code --install-extension ms-vscode.hexeditor 
code --install-extension gruntfuggly.todo-tree 
code --install-extension tamasfe.even-better-toml 
code --install-extension oderwat.indent-rainbow 
code --install-extension ms-vscode-remote.vscode-remote-extensionpack 
code --install-extension ms-vscode.pylance 
code --install-extension donjayamanne.githistory 
code --install-extension zhuangtongfa.material-theme 
code --install-extension esbenp.prettier-vscode 
code --install-extension shardulm94.trailing-spaces 
code --install-extension ritwickdey.liveserver 
code --install-extension vscode-icons-team.vscode-icons 
code --install-extension pkief.material-icon-theme 
code --install-extension dbaeumer.vscode-eslint 
code --install-extension aaron-bond.better-comments 
code --install-extension njpwerner.autodocstring 
code --install-extension mhutchie.git-graph 
code --install-extension webfreak.debug 
code --install-extension humao.rest-client 
code --install-extension mechatroner.rainbow-csv 
code --install-extension ms-toolsai.jupyter 
code --install-extension ms-toolsai.jupyter-keymap 
code --install-extension ms-toolsai.jupyter-renderers 
code --install-extension ms-toolsai.vscode-jupyter-cell-tags 
code --install-extension ms-toolsai.vscode-jupyter-slideshow