name: Install VS Code Extensions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-extensions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install VS Code
        run: |
          sudo apt update
          sudo apt install wget gpg -y
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
          sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
          sudo apt update
          sudo apt install code -y
          rm -f packages.microsoft.gpg

      - name: Run VS Code configuration script
        run: |
          chmod +x ./vscode-configuration.sh
          ./vscode-configuration.sh
